# Generated by Django 5.2.4 on 2025-07-23 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_managers'),
        ('market', '0003_storeaddress_alter_store_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='UserAddress',
        ),
        migrations.RenameIndex(
            model_name='useraddress',
            new_name='account_use_city_9c2727_idx',
            old_name='account_add_city_a74041_idx',
        ),
    ]
