# Generated by Django 5.2.4 on 2025-07-26 21:33

import base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_address_useraddress_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', base.models.SoftDeleteUserManager()),
                ('all_objects', base.models.AllUserManager()),
            ],
        ),
    ]
