# Generated by Django 5.2.4 on 2025-08-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address_line_2',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
