# Generated by Django 5.2.4 on 2025-08-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_alter_payment_card_pan_alter_payment_reference_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('confirmed', 'confirmed')], default='pending', max_length=12),
        ),
    ]
