# Generated by Django 5.2.4 on 2025-08-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_order_explanation_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeaddress',
            name='address_line_2',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
